pipeline {
    agent any
    tools {
         maven "maven3.9"
        jdk "JDK17"

    }
    
    environment {
        cluster = "vproappprod"
        service = "vprofileapptask-service-prod"
    }

    stages {
        stage('Deploy to Staging ECS'){
            steps{
                withAWS(credentials: 'aescreds', region: 'us-west-1' ){
                  sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'  
                }
            }
        }
        
    }

}